### ISSUE TITLE
bug: local coordinates are not correctly reprocuded

### ISSUE THREAD

**Issue by asalzburger** [acts-project/traccc#15]
Either input data or channelisation is wrong in the longitudinal direction, the local coordinates are not symmetric around +/- 0.

**Comment by guilhermeAlmeida1** [comment]
I believe this has been fixed a while back in https://github.com/acts-project/traccc/pull/267 and https://github.com/acts-project/acts/pull/1650 . The bins used to have a rounding propagation error on the z axis which made them assymetric.
