### ISSUE TITLE
feat: Implement ATLAS seedfinder in traccc

### ISSUE THREAD

**Issue by asalzburger** [acts-project/traccc#26]
I suggest to (re-)implement on the ATLAS seed finder(s) in `traccc` as a next algorithm to the track demonstrator. 

The implementation can be done with the `traccc` EDM in mind and without the constraints of fitting into the ACTS infrastructure per se, eventual cross-translation into `Acts::Seeds` can be done later.

**Comment by beomki-yeo** [comment]
I think this can be closed?

**Comment by stephenswat** [comment]
Indeed it can.
