### ISSUE TITLE
Adding device code to the build system

### ISSUE THREAD

**Issue by stephenswat** [acts-project/traccc#28]
I'd like to get a little discussion started about how we integrate device code into the traccc repository. We currently have at least three people working on adding device code, and I think it would be a good idea to discuss and clarify this, so we don't end up with our build system being a complete mess.

So far, I understand @beomki-yeo's approach has been to add a subdirectory at the highest level for each device type, so we would end up with a separately configurable `cpu/` and `cuda/` directory, and possibly more for other device programming paradigms. Beomki's approach also has the `example/` directory split up into multiple modules, one for each device type, giving us `examples/cuda/`. Finally, this approach has a different EDM per device type. Whether that is desirable is obviously still very much up for debate.

My approach so far has been to put all device code (including CPU) code under a new `device/` directory, giving rise to directories such as `device/cuda/` and `device/cpu`. I haven't quite decided on what to do with the examples, I think there are good things to be said about having `device/cuda/examples/` or `examples/cuda/`, and I am not sure which I prefer at this time. Currently, I am using the same EDM for CPU and device code, which I think is useful, but if it turns out to be necessary to have a dedicated device EDM, it might be useful to have the directory structure for that set up a priori.

Any thoughts on these ideas? Which one should we settle on? Obviously we can (and should) mix and match the best parts of both strategies.

**Comment by beomki-yeo** [comment]
In my latest work, which I have not pushed yet, I have also played around with unified edm suggested by @krasznaa, and now it has slightly different structure: 
cpu(core) directory is still same, but gpu architectures are moved into gpu directory, e.g. gpu/cuda or gpu/sycl
The thought behind this is that there could be additional algebras/struct objects commonly required for gpu architectures (so gpu/common could be considered at some point). Of course this is going to be more obvious when sycl development is done parallelly

**Comment by beomki-yeo** [comment]
Hmm. One of the options I could suggest having structures like this:
![image](https://user-images.githubusercontent.com/63090140/115624154-10d05f80-a2af-11eb-9b8c-9b6049c31fdd.png)

or 

![image](https://user-images.githubusercontent.com/63090140/115624231-2e052e00-a2af-11eb-92dd-f5a1da553fa8.png)

where `common` directory can be compiled with gpu to utilize the functions defined for algebras and geometries inside kernels.
