### ISSUE TITLE
Unifying algorithm semantic for different APIs

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/traccc#31]
The current cpu code for ccl function is defined in the following way:
`traccc::cluster_collection clusters = traccc::component_connection(traccc::cell_collection cells)`
where the iteration over modules is required. 
Then the whole code structure will differ from GPU APIs version where we might not need to iterate over modules.

What I would like to suggest is having following unified format across the different APIs:
```
traccc::component_connection(traccc::cell_container cells, traccc::cluster_container& clusters)
traccc::cuda::component_connection(traccc::cell_container cells, traccc::cluster_container& clusters)
traccc::sycl::component_connection(traccc::cell_container cells, traccc::cluster_container& clusters)
```
If someone has different ideas or suggestions please leave some comments

**Comment by stephenswat** [comment]
I would propose that we unify all algorithms in `traccc` under a standard interface, something like:

```cpp
template<typename I, typename O>
class algorithm {
    void operator(const I & i, O & o);
};
```

Then, our algorithms can inherit from this class to provide us a consistent API:

```cpp
namespace traccc::cuda {
    class component_connection : public algorithm<cell_container, cluster_container> {
        ...
    };
}
```

This would allow us to define compile-type types for composition, while allowing algorithm selection at runtime:

```cpp
template<typename I, typename P, typename O>
class composition : public algorithm<I, O> {
    composition(algorithm<I, P> & a1, algorithm<P, O> & a2);
};
```

If we want to extend this concept, we can additionally define data location at compile time:

```cpp
template<typename I, typename O, storage Is=AGNOSTIC, storage Os=AGNOSTIC>
class algorithm {
    void operator(const I & i, O & o);
};
```

**Comment by beomki-yeo** [comment]
I do like your suggestion. 
Since even single algorithm may require various types of containers, can input and output type contain more than one container? For example:
```c++
template< typename I, typename O >  
class algorithm{    
public:
    virtual void operator()(const I& i, O& o){
        
    }
};

struct input_t{
    host_cell_container a;
    host_measurement_container b;
};

struct output_t{
    host_spacepoint_container b;
};

class test: public algorithm<input_t, output_t>{    
    
public:
    void operator()(const input_t& I, output_t& O) override {
        ...
    }
    
};
```
Of course the above code will force us to apply `get_data()` to every members of structure so it may not be a good solution.:p
