### ISSUE TITLE
Add double precision build in CI

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/traccc#404]
It seems traccc CI is not running with `TRACCC_CUSTOM_SCALARTYPE=double && DETRAY_CUSTOM_SCALARTYPE=double` option. Is it intended or can we simply add it?

**Comment by stephenswat** [comment]
Hi Beomki, we can add a double-precision build quite easily. However, I think it would be wise to keep the number of builds in check; our CI already consumes about 3 runner-hours for every build, so simply doubling the number of builds would be a lot of added work. We can think about adding double-precision builds more specifically (i.e. only for one specific CUDA job). I would also like to reduce the number of jobs in general, and reduce the cost of compilation by pre-compiling some dependencies into a custom image, but those are things we can look at later.

**Comment by beomki-yeo** [comment]
I still worry that the project is not compiled with double precision or having weird physics results unless it is not included in the CI.
We don't have to add double precision for every CI build. one from CPU and one from CUDA build will be enough.
