### ISSUE TITLE
Single muon events fail to construct any seeds

### ISSUE THREAD

**Issue by stephenswat** [acts-project/traccc#413]
As discussed in the EF Tracking meeting this Monday, Shima (whose GitHub handle I do not have) has been running into an issue where very simple single-muon events are failing to generate seeds. Spacepoint files which reproduce this failure are [event000000280-spacepoints.csv](https://github.com/acts-project/traccc/files/11676453/event000000280-spacepoints.csv) and [event000000114-spacepoints.csv](https://github.com/acts-project/traccc/files/11676454/event000000114-spacepoints.csv). Both of these tracks have very similar parameter, namely θ = 1.42 and 1.34, φ = 0.32 and 0.36, and z<sub>0</sub> = 98.2mm and 97.9mm. We should aim to understand why these (trivial) tracks fail to reconstruct.

Shima has hinted that these seeds fail to be made due to the `dCotThetaMinusError2` cut. This could be the result of some catastrophic cancellation, but the cause is not clear to me at this time.

**Comment by shimasnd** [comment]
A minor additional info of this issue is that the setting for the seed filtering (i.e. seeding_config.hpp values) are loosened to cover the detector geometry, in which these single muon events are simulated. 
![image](https://github.com/acts-project/traccc/assets/84299713/a14c25de-789e-45c9-b9f3-2021ead12a16)
Many thanks for your investigation.

**Comment by beomki-yeo** [comment]
How often does this happen? And how do we can reproduce the input spacepoint file?

**Comment by stephenswat** [comment]
My understanding is this happens deterministically for the given spacepoint files.

**Comment by shimasnd** [comment]
These are actually ATLAS single muon events. The global coordinates of the ATLAS pixel clusters are treated as spacepoints and are used to test the traccc seeding process. They are not in traccc-data. I got these 2 events from 500 single muon events, which are generated in 0.1<eta<0.3, 0.3<phi<0.5, and z0 ranging over +-300mm.

**Comment by beomki-yeo** [comment]
Thanks for the info. Could you also check the truth z0 of the particles which fail the reconsturction? I guess the default seeding config parameter should be changed to cover 300 mm range of z0

**Comment by shimasnd** [comment]
As Stephen wrote in his first comment, the truth track values of these two events are:
"namely θ = 1.42 and 1.34, φ = 0.32 and 0.36, and z0 = 98.2mm and 97.9mm"
They fail at the triplet production. 
In my test, the config parameters are loosened. For the values, please see my comment above (https://github.com/acts-project/traccc/issues/413#issuecomment-1581726671). 

(For other 498 events, seeds are properly reconstructed even for muons with larger |z0| values and comparison to the truth looks reasonable. I attach one of the plots.)
[0530z0SeedTrue.pdf](https://github.com/acts-project/traccc/files/11705676/0530z0SeedTrue.pdf)

**Comment by beomki-yeo** [comment]
Thanks I will take a look into this issue ASAP
