### ISSUE TITLE
Detector file configuration is ambiguously defined

### ISSUE THREAD

**Issue by stephenswat** [acts-project/traccc#452]
The detector configuration file is multiply defined in the following files:

1. https://github.com/acts-project/traccc/blob/main/examples/options/src/options/common_options.cpp#L29
2. https://github.com/acts-project/traccc/blob/main/examples/options/src/options/full_tracking_input_options.cpp#L14

In examples like the CUDA seq example, this causes the entire executable to break, as reported by the ATLAS HTL team who are trying to experiment with traccc.

**Comment by stephenswat** [comment]
@beomki-yeo I know you have been doing some refactoring work on the options do you have an opinion on how best to fix this?

**Comment by beomki-yeo** [comment]
One in the full tracking option needs to be removed.
