### ISSUE TITLE
GPU CI machine appears to be broken

### ISSUE THREAD

**Issue by stephenswat** [acts-project/traccc#635]
See https://github.com/acts-project/traccc/pull/631/checks?check_run_id=26806520473.

**Comment by stephenswat** [comment]
@paulgessinger did we make any changes to the way this machine runs at all that might have caused this?

**Comment by paulgessinger** [comment]
The nvidia driver just self-destructed. I reinstalled it and the container runtime, and it seems to be working again.

**Comment by stephenswat** [comment]
Thanks heaps!
