### ISSUE TITLE
Benchmarks Attempt to Run on Forks (2024.08.20.)

### ISSUE THREAD

**Issue by krasznaa** [acts-project/traccc#687]
I just now updated the `main` branch of my fork to the latest version of the code. And got:

https://github.com/krasznaa/traccc/actions/runs/10472048984

The CI setup needs to check not only that it would run on the `main` branch, but also that it would be the main repository.

I did it like the following in VecMem: https://github.com/acts-project/vecmem/blob/main/.github/workflows/pages.yml#L32

**Comment by beomki-yeo** [comment]
Thank you This is a great catch! I just opened #688 :wink:
