### ISSUE TITLE
Kalman Fitter Changes the Charge of Tracks Unexpectedly

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/traccc#724]
The sign of q/p can be changed in the calculation of new bound track parameter in `gain_matrix_updater`

https://github.com/acts-project/traccc/blob/0a16362e7a202473d062b80449b0f3cadfd2030d/core/include/traccc/fitting/kalman_filter/gain_matrix_updater.hpp#L111C1-L125C47

This causes an assertion error that the sign of q/p and hypothesized particle's charge gets different. It should be fixed by either aborting the track or changing the particle's charge together.  I think I will just abort the track given that this only happens for bad estimation of seed parameters.

**Comment by stephenswat** [comment]
Right now this makes it impossible to run the code in debug mode. Does it make sense to remove the assertion, particularly following the conversation in the last parallelization meeting?

**Comment by beomki-yeo** [comment]
OK I can make a fix soon
