### ISSUE TITLE
`const` input type of `algorithm` class for `non-const` device input

### ISSUE THREAD

**Issue by beomki-yeo** [acts-project/traccc#77]
One issue has been raised by [PR46](https://github.com/acts-project/traccc/pull/46#discussion_r685825190) where we can not use `algorithm` class for GPU because non-const vecmem function (`get_data()`) is called for const input data types. It might be very convenient if we just remove `const` qualifier in input data type but not sure if it is the best way for this

**Comment by beomki-yeo** [comment]
@paulgessinger  is geometry data okay to be const ? I don't know very well about how geometry alignment is handled in acts

**Comment by paulgessinger** [comment]
So in ACTS we have the geometry data as const, and the recommended way to handle alignment is via explicit context objects that are passed through the call hierarchy. They contain a way for the detector elements receiving transform queries to talk to whatever conditions backend an experiment uses to retrieve the aligned transforms.

The alignment code we currently have in core, however, currently uses a different mechanism, where the geometry is marked as const, but is actually modified behind the scenes by the alignment algorithm.

I don't have a good idea what the alignment story could look like for traccc and related efforts. My immediate feeling would be to keep the geometry const for now, but that might have to be revisited at some point.
